### ISSUE TITLE
Custom Output Directory

### ISSUE THREAD

**Issue by rymesaint** [hahouari/inno_bundle#8]
can you add some options to change custom output directory?

**Comment by hahouari** [comment]
I went with flutter conventions, `flutter build windows` command does not have an a cli parameter for a custom output directory, besides, it would be easier and less code and checks to just add a copy command after `inno_bundle:build` like this
```sh
dart run inno_bundle:build --release
cp -r build\windows\x64\installer\Release C:\custom\output\directory
```
